version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresbrndb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/:/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
        context: app
        dockerfile: Dockerfile
    container_name: assignmentsexchangeapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "PYTHONPATH=. uvicorn main:app --host 0.0.0.0 --port 8000 --reload" ]

volumes:
  postgres_data:
